# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc3cb18e04412cc6725727d6c8171513"
name = "hkbbwall"
handle = "hkbbwall"
application_url = "https://employment-edit-studios-pic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "betzie.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://employment-edit-studios-pic.trycloudflare.com/auth/callback",
  "https://employment-edit-studios-pic.trycloudflare.com/auth/shopify/callback",
  "https://employment-edit-studios-pic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
